### ISSUE TITLE
Requirement.txt please

### ISSUE THREAD

**Issue by Cht666-412** [xandery-geek/BackdoorAttacks#2]
需要requirements.txt，自己conda里torch版本和pytorch_lightning版本貌似不兼容，但不知道如何解决

**Comment by xandery-geek** [comment]
好，今晚我会release一下requirements.txt文件

**Comment by xandery-geek** [comment]
> 需要requirements.txt，自己conda里torch版本和pytorch_lightning版本貌似不兼容，但不知道如何解决

requirements.txt已经传上来了，看一下能不能解决你的问题

**Comment by Cht666-412** [comment]
> 好，今晚我会release一下requirements.txt文件



> > 需要requirements.txt，自己conda里torch版本和pytorch_lightning版本貌似不兼容，但不知道如何解决
> 
> requirements.txt已经传上来了，看一下能不能解决你的问题

感谢
